### ISSUE TITLE
xorg-libx11 ~ 1.6

### ISSUE THREAD

**Issue by meiyasan** [conda-forge/xorg-libxp-feedstock#7]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Hello,

I have some issues about xorg-libxp that I can't debug by myself.
I just created a fresh environment and can't get this command working: 
```
(base) conda install "xorg-libxp" "xorg-libx11>1.8" 
Channels:
 - hep-forge
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package xorg-libxp-1.0.3-hd590300_1002 requires xorg-libx11 1.6.*, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ xorg-libx11 >=1.8 * is requested and can be installed;
└─ xorg-libxp =* * is not installable because it requires
   └─ xorg-libx11 =1.6 *, which conflicts with any installable versions previously reported.
```

The recipe meta.yml for xorg-libxp is fixing xorg-libx11 to 1.8*, but from anaconda package is in conflict with xorg-libx11. 
It seems xorg-libxp is not in sync with (build number = 1003 in the last version) although have minimal requirement. 

### Installed packages

```shell
(myenv) conda list
# packages in environment at /opt/conda/envs/myfitter/envs/myenv:
#
# Name                    Version                   Build  Channel
```

### Environment info

```shell
[13:52:02] root@docker:986ecfea4134:/opt/conda/envs/myfitter/conda-bld/debug_1734442543705/work $ 
(myenv) conda info

     active environment : myenv
    active env location : /opt/conda/envs
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 24.11.1
    conda-build version : 24.11.2
         python version : 3.12.8.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=24.11.1=0
                          __glibc=2.39=0
                          __linux=6.10.14=0
                          __unix=0=0
       base environment : /opt/conda/envs/myenv  (writable)
      conda av data dir : /opt/conda/envs/myenv/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/envs/myfitter/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs/myfitter/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/24.11.1 requests/2.32.3 CPython/3.12.8 Linux/6.10.14-linuxkit ubuntu/24.04.1 glibc/2.39 solver/libmamba conda-libmamba-solver/24.11.1 libmambapy/2.0.5
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by meiyasan** [comment]
I tried to force using build 1003, but it definitely doesn't seems to match the meta.yaml file

```
(base) conda install "xorg-libxp=1.0.3=*_1003" "xorg-libx11>=1.8" 
Channels:
 - hep-forge
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package xorg-libxp-1.0.3-hd590300_1003 requires xorg-libx11 1.6.*, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ xorg-libx11 >=1.8 * is requested and can be installed;
└─ xorg-libxp ==1.0.3 *_1003 is not installable because it requires
   └─ xorg-libx11 =1.6 *, which conflicts with any installable versions previously reported.
```

**Comment by pkgw** [comment]
This recipe needs a refresh to align with updates to the rest of the X.org family. I'll look into doing so.

**Comment by pkgw** [comment]
Ahh, OK. There is a new release of libXp that we're not distributing, which would provide a good excuse to update the package, but it comes with a deprecation notice:

> This library provides support for X11 clients to print via the X Print
> Extension, as previously implemented in the Xprt server.  X.Org removed
> support for the Xprt server from the xorg-server releases in the 1.6.0
> release in 2009, and the standalone git repo it was moved to has been
> unmaintained since 2009, making it difficult to actually use this library.
>
> While X.Org has continued to maintain this library for binary compatibility,
> we do not plan to do so for the long term and encourage anyone still building
> or shipping it to investigate how to stop doing so going forward as we now
> consider it to be deprecated.

We *could* issue an update to this package, but it is unlikely that any current software truly needs the functionality provided by this library. What are you doing that is requiring libXp to be available?

**Comment by meiyasan** [comment]
I am not sure this is related to, but `meta.yaml` goes like:
```
build:
  number: 1003
[..]
requirements:
[..]
  host:
    - pthread-stubs
    - xorg-xextproto
    - xorg-printproto
    - xorg-util-macros  # [win]
    - xorg-libx11 1.8.*
    - xorg-libxau
    - xorg-libxext
  run:
    - xorg-libx11 1.8.*
    - xorg-libxau
    - xorg-libxext
```

however, `xorg-libx11` is pinned to `xorg-libx11 1.6.*`, when installing `xorg-libxp` package. So my guess is that conda is not in sync with the latest recipe provided by `xorg-libxp-feedstock`. In meta.yml and looking in anaconda website, both build number are `1003`

**Comment by pkgw** [comment]
My question is different: why do you need libXp in the first place? My best understanding is that it has been deprecated for a long time, and there ought not be any current software that even needs it. It would be better to fix that side of things, if possible.

**Comment by meiyasan** [comment]
I believe X11 is largely phased out in favor of Wayland or other modern technologies, but I understood your concerns. The main goal is to support legacy software that isn’t actively maintained but is being modernized. Conda simplifies this process while offering straightforward configuration for the users managing the updates.

xorg-libx11 1.6-1.8 are all good enough, so it would be great to have all of these consistently pinned to the same 1.8 version.

**Comment by pkgw** [comment]
I am asking about libXp, the library implementing the X11 printing protocol, in particular. There's still a lot of software that depends on X11, even if it is probably on its way out, but the X print protocol extension and library have been deprecated for something like 15 years.

If you have needs external to conda-forge that truly need libxp, we can work to provide it, but if there is anything in conda-forge that seems to depend on libXp, that dependency is probably spurious and ought to be removed.

**Comment by pkgw** [comment]
I've triggered a build of the latest upstream version, 1.0.4, that should be properly pinned to the 1.8 series of libx11.

**Comment by meiyasan** [comment]
Thank you, it worked like a charm!
